version: '3.9d'
services:
  api1: # API - Instância 01
    image: localhost/rinha-de-backend:1.0.1
#    build:
#      context: .
#      dockerfile: Dockerfile
    hostname: api1
    environment:
      - DB_HOST=mongo
      - DB_PORT=27017
      - DB_NAME=test
    depends_on:
      - db
    network_mode: "host"
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '768M'

  api2: # API - Instância 01
    image: localhost/rinha-de-backend:1.0.1
#    build:
#      context: .
#      dockerfile: Dockerfile
    hostname: api2
    environment:
      - DB_HOST=mongo
      - DB_PORT=27017
      - DB_NAME=test
      - SERVER_PORT=8081
    depends_on:
      - db
    network_mode: "host"
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '768M'

  nginx: # Load Balancer
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    network_mode: "host"
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '256M'

  db:
    image: mongo
    container_name: mongo
    hostname: mongo
    ports:
      - "27017:27017"
    network_mode: "host"
    deploy:
      resources:
        limits:
          cpus: '0.95'
          memory: "512M"