spring:
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-missing-creator-properties: true
  data:
    mongodb:
      database: "${DB_NAME:test}"
      host: "${DB_HOST:localhost}"
      port: "${DB_PORT:27017}"
      uri: "mongodb://${DB_HOST:localhost}/${DB_NAME:test}"
      auto-index-creation: true
springdoc:
  swagger-ui:
    path: /docs
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true