### Exemplos de requisições válidas para o endpoint de pessoas
POST http://localhost:9999/pessoas
Content-Type: application/json

{
  "apelido" : "ana",
  "nome" : "ana",
  "nascimento" : "1985-09-23",
  "stack" : null
}

### Total de pessoas cadastradas
GET http://localhost:9999/contagem-pessoas